<a href="https://colab.research.google.com/github/adrinorosario/pytorch-notebooks/blob/main/0_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PyTorch Fundamentals

In [ ]:
!nvidia-smi

Mon Oct  7 11:29:44 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.4.1+cu121


## Introduction to Tensors

### Creating Tensors

In [ ]:
#scalar
scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
scalar.item()

tensor(7)
0


7

In [ ]:
#Vector
vector = torch.tensor([7, 7])
print(vector.ndim)
vector.shape

1


torch.Size([2])

In [ ]:
#Matrix
MATRIX = torch.tensor([[5,3], [4, 2]])
MATRIX

tensor([[5, 3],
        [4, 2]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([5, 3])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#Tensor
TENSOR = torch.tensor([[[1,2], [4,5], [7,8]],
                       [[11,12], [14,15], [17,19]],
                       [[1, 3], [31, 1], [13,331]],
                       [[1, 2], [12, 13], [1223, 2]]])
TENSOR

tensor([[[   1,    2],
         [   4,    5],
         [   7,    8]],

        [[  11,   12],
         [  14,   15],
         [  17,   19]],

        [[   1,    3],
         [  31,    1],
         [  13,  331]],

        [[   1,    2],
         [  12,   13],
         [1223,    2]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([4, 3, 2])

In [ ]:
TENSOR[0]

tensor([[1, 2],
        [4, 5],
        [7, 8]])

In [ ]:
TENSOR[0][1]

tensor([4, 5])

In [ ]:
TENSOR[1][2][0]

tensor(17)

### Random Tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and adjust those random numbers to better understand the data

`Start with random numbers -> Look at data -> Update random numbers -> Look at data -> Update random numbers`

In [ ]:
#Create random tensor of size() or shape()
random_tensor = torch.rand(3, 4, 5, dtype=float)
random_tensor

tensor([[[0.7761, 0.8608, 0.1004, 0.5921, 0.5394],
         [0.1564, 0.1477, 0.6926, 0.4510, 0.3454],
         [0.4409, 0.3907, 0.1904, 0.5324, 0.5773],
         [0.2412, 0.4417, 0.3922, 0.7849, 0.4086]],

        [[0.2007, 0.5906, 0.6062, 0.2820, 0.8035],
         [0.8577, 0.2463, 0.7846, 0.7726, 0.0772],
         [0.6902, 0.8788, 0.9598, 0.0717, 0.5538],
         [0.0441, 0.7811, 0.7455, 0.3383, 0.9378]],

        [[0.8361, 0.2726, 0.0191, 0.8149, 0.5374],
         [0.6516, 0.4727, 0.2830, 0.8601, 0.6963],
         [0.8432, 0.0412, 0.4680, 0.9296, 0.5863],
         [0.0555, 0.0561, 0.8282, 0.0756, 0.0458]]], dtype=torch.float64)

In [ ]:
random_tensor.ndim

3

In [ ]:
random_tensor.shape

torch.Size([3, 4, 5])

In [ ]:
#Random tensor with shape similar to an image tensor
random_image_size_tensor = torch.rand(size=(453, 413, 3)) # height, width, color channels (R,G,B)
random_image_size_tensor

tensor([[[0.9928, 0.2879, 0.4258],
         [0.2613, 0.0878, 0.6542],
         [0.7549, 0.9564, 0.8425],
         ...,
         [0.8734, 0.0708, 0.9670],
         [0.6528, 0.8912, 0.7678],
         [0.3298, 0.7915, 0.1912]],

        [[0.7660, 0.8822, 0.5622],
         [0.3777, 0.8801, 0.8483],
         [0.0606, 0.4710, 0.7136],
         ...,
         [0.7239, 0.6135, 0.9045],
         [0.8312, 0.1161, 0.0402],
         [0.6504, 0.4120, 0.6067]],

        [[0.9941, 0.6604, 0.6480],
         [0.4022, 0.5152, 0.7378],
         [0.3947, 0.8639, 0.9577],
         ...,
         [0.2406, 0.5760, 0.2039],
         [0.5239, 0.3425, 0.3480],
         [0.8493, 0.4768, 0.4348]],

        ...,

        [[0.2025, 0.4168, 0.7616],
         [0.8712, 0.8270, 0.9936],
         [0.5042, 0.0460, 0.2015],
         ...,
         [0.9239, 0.3512, 0.5101],
         [0.5205, 0.2521, 0.3125],
         [0.7969, 0.8151, 0.8763]],

        [[0.4586, 0.1685, 0.8667],
         [0.3963, 0.7254, 0.3214],
         [0.

In [ ]:
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([453, 413, 3]))

### Zeros and Ones

In [ ]:
zeros = torch.zeros(3, 4, 5)
zeros

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [ ]:
zeros * random_tensor

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], dtype=torch.float64)

In [ ]:
ones = torch.ones(3, 4, 5)
ones * random_tensor

tensor([[[0.7761, 0.8608, 0.1004, 0.5921, 0.5394],
         [0.1564, 0.1477, 0.6926, 0.4510, 0.3454],
         [0.4409, 0.3907, 0.1904, 0.5324, 0.5773],
         [0.2412, 0.4417, 0.3922, 0.7849, 0.4086]],

        [[0.2007, 0.5906, 0.6062, 0.2820, 0.8035],
         [0.8577, 0.2463, 0.7846, 0.7726, 0.0772],
         [0.6902, 0.8788, 0.9598, 0.0717, 0.5538],
         [0.0441, 0.7811, 0.7455, 0.3383, 0.9378]],

        [[0.8361, 0.2726, 0.0191, 0.8149, 0.5374],
         [0.6516, 0.4727, 0.2830, 0.8601, 0.6963],
         [0.8432, 0.0412, 0.4680, 0.9296, 0.5863],
         [0.0555, 0.0561, 0.8282, 0.0756, 0.0458]]], dtype=torch.float64)

### Creating a range of tensors and tensors-like

In [ ]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(start=0, end=1010, step=12)

tensor([   0,   12,   24,   36,   48,   60,   72,   84,   96,  108,  120,  132,
         144,  156,  168,  180,  192,  204,  216,  228,  240,  252,  264,  276,
         288,  300,  312,  324,  336,  348,  360,  372,  384,  396,  408,  420,
         432,  444,  456,  468,  480,  492,  504,  516,  528,  540,  552,  564,
         576,  588,  600,  612,  624,  636,  648,  660,  672,  684,  696,  708,
         720,  732,  744,  756,  768,  780,  792,  804,  816,  828,  840,  852,
         864,  876,  888,  900,  912,  924,  936,  948,  960,  972,  984,  996,
        1008])

In [ ]:
# Creating tensors-like
random_tensor.shape
new_random_tensor = torch.zeros_like(input=random_tensor)
new_random_tensor

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], dtype=torch.float64)

### Tensor Datatypes

**Note**: Tensor datatypes is one of the 3 big isssues you'll run into with PyTorch & Deep Learning

1. Tensors are not the right datatype
2. Tensors are not the right shape
3. Tensors are not on the right device

In [ ]:
float_32_tensor = torch.tensor([2.3, 31.2, 4.2],
                               dtype=torch.float64,
                               device=None,
                               requires_grad=False) # to track the gradients of a tensor when it goes through certain numerical calculations
float_32_tensor.dtype

torch.float64

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor * float_32_tensor

tensor([  5.2918, 973.5375,  17.6367], dtype=torch.float64)

In [ ]:
int32_tensor  = float_32_tensor.type(torch.int32)
int32_tensor

tensor([ 2, 31,  4], dtype=torch.int32)

In [ ]:
float_32_tensor * int32_tensor

tensor([  4.6000, 967.2000,  16.8000], dtype=torch.float64)

### Getting information from tensors

1. Tensors are not the right datatype -  to get the datatype use `tensor.dtype`
2. Tensors are not the right shape - to get the shape use `tensor.shape`
3. Tensors are not on the right device - to get the device use `tensor.device`

In [ ]:
some_tensor = torch.rand(3, 4, dtype=torch.float16)
some_tensor

tensor([[0.1646, 0.2334, 0.2720, 0.4951],
        [0.5659, 0.2837, 0.6265, 0.8262],
        [0.4585, 0.3350, 0.4204, 0.6411]], dtype=torch.float16)

In [ ]:
some_tensor.dtype, some_tensor.shape, some_tensor.device, some_tensor.size()
some_tensor.to("cuda")

tensor([[0.1646, 0.2334, 0.2720, 0.4951],
        [0.5659, 0.2837, 0.6265, 0.8262],
        [0.4585, 0.3350, 0.4204, 0.6411]], device='cuda:0',
       dtype=torch.float16)

### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing matrix multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [ ]:
torch.rand(2, 3).shape, torch.rand(3, 2).shape
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.2469, 0.5035],
        [0.3938, 0.7663]])

In [ ]:
# Element wise
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
torch.matmul(int32_tensor, float_32_tensor.type(torch.int32))

tensor(981, dtype=torch.int32)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 619 µs, sys: 906 µs, total: 1.52 ms
Wall time: 1.26 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 279 µs, sys: 0 ns, total: 279 µs
Wall time: 256 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_a = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

# tensor_b = torch.tensor([[7, 10, 9],
#                          [11, 20, 10]])

tensor_b = torch.tensor([[7, 10],
                         [9, 11],
                         [20, 10]])

torch.mm(tensor_a, tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
print(f"Original shape of tensor_a: {tensor_a.shape}")
print(f"Original shape of tensor_b: {tensor_b.shape}")

Original shape of tensor_a: torch.Size([3, 2])
Original shape of tensor_b: torch.Size([3, 2])


To fix the tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.
A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_b

tensor([[ 7, 10],
        [ 9, 11],
        [20, 10]])

In [ ]:
print(f"Shape of tensor_b after transposing: {tensor_b.T.shape}")

Shape of tensor_b after transposing: torch.Size([2, 3])


In [ ]:
print(f"Multiplying tensor_a: {tensor_a.shape} and tensor_b: {tensor_b.T.shape}: ")
print(f"Output = {torch.mm(tensor_a, tensor_b.T)}")
print(f"Shape of the output: {torch.mm(tensor_a, tensor_b.T).shape}")

Multiplying tensor_a: torch.Size([3, 2]) and tensor_b: torch.Size([2, 3]): 
Output = tensor([[ 27,  31,  40],
        [ 61,  71, 100],
        [ 95, 111, 160]])
Shape of the output: torch.Size([3, 3])


In [ ]:
# Transposing tensor_a instead of tensor_b
print(f"Original shape of tensor_a: {tensor_a.shape}")
print(f"Shape of tensor_a after transposing: {tensor_a.T.shape}\n")

print("tensor_a @ tensor_b equals: \n")
print(torch.matmul(tensor_a.T, tensor_b))

print(f"\nShape of the output: {torch.matmul(tensor_a.T, tensor_b).shape}")

Original shape of tensor_a: torch.Size([3, 2])
Shape of tensor_a after transposing: torch.Size([2, 3])

tensor_a @ tensor_b equals: 

tensor([[134,  93],
        [170, 124]])

Shape of the output: torch.Size([2, 2])


### Tensor aggregation: Finding the min, mean, max, sum, etc

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# The torch.mean() requires a tensor with dtype of float32
torch.min(x), x.max(), torch.mean(x.type(torch.float32), dtype=torch.float64)

(tensor(0), tensor(90), tensor(45., dtype=torch.float64))

In [ ]:
# Finding the positional min and positional max -> returns index position of the target tensor
torch.argmin(x), torch.argmax(x), x[torch.argmin(x)], x[torch.argmax(x)]

(tensor(0), tensor(9), tensor(0), tensor(90))

## Reshaping, Stacking, Squeezing and Unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side-by-side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
#x_reshaped = x.reshape(2, 5)
x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [ ]:
# Change the view
# A view shares the original memory with the tensor -> changing z changes x
z = x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
z[:, 0] = 11
z, x

(tensor([[11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([11.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[11., 11., 11., 11.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [ ]:
y = torch.zeros(2, 1, 2, 1, 2)
print(f"Shape of y before squeezing: {y.shape}")
y = torch.squeeze(y)
print(f"Shape of y after squeezing: {y.shape}")

Shape of y before squeezing: torch.Size([2, 1, 2, 1, 2])
Shape of y after squeezing: torch.Size([2, 2, 2])


In [ ]:
print(f"x_reshaped before unsqueezing: {x_reshaped}")
print(f"Shape of x_reshaped before: {x_reshaped.shape}\n")
x_reshaped = torch.unsqueeze(x_reshaped, 0)
print(f"\nx_reshaped after unsqueezing: {x_reshaped}")
print(f"Shape of x_reshaped after: {x_reshaped.shape}")

x_reshaped before unsqueezing: tensor([[11.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])
Shape of x_reshaped before: torch.Size([5, 2])


x_reshaped after unsqueezing: tensor([[[11.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]])
Shape of x_reshaped after: torch.Size([1, 5, 2])


In [ ]:
print(f"Shape of x_reshaped before: {x_reshaped.shape}\n")
print(torch.squeeze(x_reshaped))
x_reshaped = torch.squeeze(x_reshaped)
print(f"Shape of x_reshaped after: {x_reshaped.shape}")

Shape of x_reshaped before: torch.Size([1, 5, 2])

tensor([[11.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])
Shape of x_reshaped after: torch.Size([5, 2])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order

z = torch.rand(2, 4, 5)
z

tensor([[[0.5930, 0.9052, 0.9111, 0.3469, 0.8974],
         [0.8161, 0.5413, 0.4940, 0.8940, 0.5689],
         [0.2071, 0.9022, 0.6076, 0.3267, 0.4344],
         [0.9057, 0.8506, 0.2626, 0.4675, 0.1541]],

        [[0.5426, 0.5331, 0.2709, 0.3703, 0.2364],
         [0.9087, 0.9904, 0.2192, 0.6799, 0.1310],
         [0.6254, 0.7380, 0.4091, 0.8553, 0.4952],
         [0.9348, 0.8710, 0.2025, 0.3018, 0.6501]]])

In [ ]:
print(f"Shape of z before permuting: {z.shape}\n")
z = torch.permute(z, (1, 0, 2)) # rearranging the the three dimensions ,i.e., 2, 4, 5 in the order 4, 2, 5
print(z)
print(f"\nShape of z after permuting: {z.shape}")

Shape of z before permuting: torch.Size([2, 4, 5])

tensor([[[0.5930, 0.9052, 0.9111, 0.3469, 0.8974],
         [0.5426, 0.5331, 0.2709, 0.3703, 0.2364]],

        [[0.8161, 0.5413, 0.4940, 0.8940, 0.5689],
         [0.9087, 0.9904, 0.2192, 0.6799, 0.1310]],

        [[0.2071, 0.9022, 0.6076, 0.3267, 0.4344],
         [0.6254, 0.7380, 0.4091, 0.8553, 0.4952]],

        [[0.9057, 0.8506, 0.2626, 0.4675, 0.1541],
         [0.9348, 0.8710, 0.2025, 0.3018, 0.6501]]])

Shape of z after permuting: torch.Size([4, 2, 5])


In [ ]:
# permuting is commonly used with images
x_original = torch.rand(size=(224, 224, 3)) # (height, width, colour channels)
print(f"Previous shape: {x_original.shape}\n")
# permute the original tensor to rearrange the axis (or dim) order
x_permuted = torch.permute(x_original, (1, 2, 0)) # (width, colour channels, height)
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])

New shape: torch.Size([224, 3, 224])


In [ ]:
x_permuted[0, 0, 0], x_original[0, 0, 0]

(tensor(0.0158), tensor(0.0158))

In [ ]:
x_original[0, 0, 0] = 2324
x_permuted[0, 0, 0], x_original[0, 0, 0]

(tensor(2324.), tensor(2324.))

## Indexing(selecting data from tensors)

Indexing with pytorch is similar to that done with numpy arrays

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x.shape, x

(torch.Size([1, 3, 3]),
 tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[0, 2, 2]

tensor(9)

In [ ]:
x[:, 2:, 2:]

tensor([[[9]]])

In [ ]:
# get all values of the 0th dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# get index 0 of the 0th and 1st dimension and all values of the 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# select 3, 6, 9
x[:, :, 2:]

tensor([[[3],
         [6],
         [9]]])

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

## PyTorch tensors and NumPy

* Data in numpy array, want in pytorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
array.dtype, tensor.dtype
# when converting from numpy->pytorch, pytorch reflects the default float6 dtype unless specified otherwise

(dtype('float64'), torch.float32)

In [ ]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
numpy_tensor = torch.Tensor.numpy(tensor)
numpy_tensor # reflects dtype of the pytorch tensor

array([1., 2., 3., 4., 5., 6., 7.], dtype=float32)

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([3., 4., 5., 6., 7., 8., 9.]),
 array([1., 2., 3., 4., 5., 6., 7.], dtype=float32))

## Reproducibility (trying to take random out of random)

PyTorch reproducibility refers to the ability to obtain the same results when running your PyTorch code multiple times, given the same input data
and model architecture. This is crucial for debugging, comparing experiments, and ensuring the reliability of your research.

In short, how a neural network learns:
* Start with random numbers
* Perform tensor operations
* Update random numbers to try and make them better representations of the data
* Repeat again and again

To reduce the randomness in neural networks and pytorch comes the concept of a **random seed**.

Essentially, what the random seed does is "flavour" the randomness.

In [ ]:
torch.rand(3, 3) # psuedo randomness or generated randomness

tensor([[0.0763, 0.8194, 0.4481],
        [0.6154, 0.6969, 0.0658],
        [0.2542, 0.4064, 0.5890]])

In [ ]:
tensor1 = torch.rand(3, 4)
tensor2 = torch.rand(3, 4)
print(tensor1, "\n")
print(tensor2, "\n")
print(tensor1 == tensor2)

tensor([[0.4960, 0.6651, 0.3087, 0.3495],
        [0.8657, 0.3253, 0.2600, 0.2177],
        [0.0628, 0.2908, 0.6067, 0.3075]]) 

tensor([[0.7022, 0.6743, 0.8295, 0.6541],
        [0.8182, 0.3949, 0.9712, 0.6762],
        [0.7666, 0.1628, 0.5573, 0.7967]]) 

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# random but reproducible tensors

# set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor1 = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor2 = torch.rand(3, 4)

print(random_tensor1, "\n")
print(random_tensor2, "\n")
print(random_tensor1 == random_tensor2)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) 

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) 

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on GPUs (and making faster computations)

### Check for GPU access with pytorch

In [ ]:
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# count number of gpus
torch.cuda.device_count()

1

### Putting tensors (and models) on the GPU

In [ ]:
tensor = torch.tensor([1, 2, 4], device="cpu") # by default on the CPU
print(tensor, tensor.device)

tensor([1, 2, 4]) cpu


In [ ]:
# Move tensor to GPU if available
tensor = tensor.to(device)
print(tensor, tensor.device)

tensor([1, 2, 4], device='cuda:0') cuda:0


In [ ]:
# Moving tensors back to the CPU
#If tensor is on GPU, you can't transform it to NumPy
tensor.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
tensor = tensor.to("cpu")
print(tensor.device)
tensor.numpy()

cpu


array([1, 2, 4])

In [ ]:
import torch

In [ ]:
RANDOM_SEED = 1234

torch.manual_seed(RANDOM_SEED)
random_tensor1 = torch.rand(7, 7)

torch.manual_seed(RANDOM_SEED)
random_tensor2 = torch.rand(1, 7)

print("Random Tensor 1: \n", random_tensor1, "\n")
print("Random Tensor 2: \n", random_tensor2, "\n")

Random Tensor 1: 
 tensor([[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518],
        [0.4681, 0.6738, 0.3315, 0.7837, 0.5631, 0.7749, 0.8208],
        [0.2793, 0.6817, 0.2837, 0.6567, 0.2388, 0.7313, 0.6012],
        [0.3043, 0.2548, 0.6294, 0.9665, 0.7399, 0.4517, 0.4757],
        [0.7842, 0.1525, 0.6662, 0.3343, 0.7893, 0.3216, 0.5247],
        [0.6688, 0.8436, 0.4265, 0.9561, 0.0770, 0.4108, 0.0014],
        [0.5414, 0.6419, 0.2976, 0.7077, 0.4189, 0.0655, 0.8839]]) 

Random Tensor 2: 
 tensor([[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518]]) 



In [ ]:
random_tensor2 = torch.transpose(random_tensor2, 0, 1)
random_tensor1.shape, random_tensor2.shape

(torch.Size([7, 7]), torch.Size([7, 1]))

In [ ]:
torch.matmul(random_tensor1, random_tensor2)

tensor([[0.8613],
        [1.2761],
        [1.1540],
        [1.0134],
        [0.6783],
        [1.1122],
        [0.7266]])

In [ ]:
torch.manual_seed(RANDOM_SEED)
random_tensor3 = torch.rand(2, 3)

torch.manual_seed(RANDOM_SEED)
random_tensor4 = torch.rand(2, 3)

print("Random Tensor 3: \n", random_tensor3, "\n")
print("Random Tensor 4: \n", random_tensor4, "\n")

Random Tensor 3: 
 tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) 

Random Tensor 4: 
 tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) 



In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
random_tensor3 = random_tensor3.to(device)
random_tensor4 = random_tensor4.to(device)

random_tensor3.device, random_tensor4.device

(device(type='cuda', index=0), device(type='cuda', index=0))

In [ ]:
random_tensor3.shape, random_tensor4.T.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [ ]:
random_tensor4 = random_tensor4.T

torch.matmul(random_tensor3, random_tensor4)

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

In [ ]:
torch.matmul(random_tensor3, random_tensor4).max()

tensor(0.6287, device='cuda:0')

In [ ]:
torch.matmul(random_tensor3, random_tensor4).min()

tensor(0.2161, device='cuda:0')

In [ ]:
torch.matmul(random_tensor3, random_tensor4)[:, 0][1], torch.matmul(random_tensor3, random_tensor4)[:, 1][1]

(tensor(0.2161, device='cuda:0'), tensor(0.6287, device='cuda:0'))

In [ ]:
RANDOM_SEED = 7

torch.manual_seed(RANDOM_SEED)
random_tensor5 = torch.rand(1, 1, 1, 10)

torch.manual_seed(RANDOM_SEED)
andom_tensor5_copy = torch.squeeze(random_tensor5)

random_tensor5_copy.shape, random_tensor5.shape

(torch.Size([10]), torch.Size([1, 1, 1, 10]))